jobs:
  build-test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test
